/// <reference lib="dom" />
import {
	assert,
	assertEquals,
	assertExists,
	assertRejects,
	assertThrows,
} from "@std/testing/asserts";
import { installMockDom } from "../../happydom.test.ts";
import { loadIsolatedModule } from "../../load-isolated-module.test.ts";

/**
 * Filesystem path to the tutorial module under test.
 */
const TUTORIAL_PATH = new URL(
	"../../../src/salesforce/tutorial.js",
	import.meta.url,
);
/**
 * Baseline Salesforce Setup URL used to initialize the DOM harness.
 */
const DEFAULT_URL =
	"https://acme.my.salesforce-setup.com/lightning/setup/SetupOneHome/home";
/**
 * Every fallback tutorial page supported by the production module.
 */
const ALL_USABLE_PAGE_URLS = [
	"ObjectManager/Account/FieldsAndRelationships/view",
	"ObjectManager/Case/FieldsAndRelationships/view",
	"ObjectManager/Contact/FieldsAndRelationships/view",
	"ObjectManager/Opportunity/FieldsAndRelationships/view",
	"ObjectManager/Lead/FieldsAndRelationships/view",
	"ObjectManager/Task/FieldsAndRelationships/view",
	"ObjectManager/Campaign/FieldsAndRelationships/view",
	"ObjectManager/Product2/FieldsAndRelationships/view",
	"ObjectManager/Pricebook2/FieldsAndRelationships/view",
	"ObjectManager/Asset/FieldsAndRelationships/view",
	"PermSets/home",
	"OrgLoginHistory/home",
	"SecuritySession/home",
	"SecurityEvents/home",
	"SecuritySharing/home",
	"FieldAccessibility/home",
	"CommunicationTemplatesEmail/home",
	"ReportUI/home",
	"ConnectedApplication/home",
	"CompanyProfileInfo/home",
];

/**
 * Minimal translation service surface required by the tutorial.
 */
type Translator = {
	translate: (key: string) => Promise<string> | string;
};

type TutorialMessageValue = boolean | number | string | null | undefined;

type TutorialStorageValue =
	| Array<{ shortcut: string }>
	| TutorialMessageValue;

/**
 * Dependency bundle injected into the tutorial module for browserless tests.
 */
type TutorialDeps = {
	constants: Record<string, string>;
	functions: {
		performLightningRedirect: (url: string) => void;
		sendExtensionMessage: (
			message: Record<string, TutorialMessageValue>,
		) => Promise<TutorialStorageValue>;
		sendExtensionMessages: (
			messages: Array<Record<string, TutorialMessageValue>>,
		) => Promise<TutorialStorageValue[]>;
	};
	ensureTranslatorAvailability: () => Promise<Translator>;
	getTranslations: (
		keys: string | string[],
		connector?: string,
	) => Promise<string | string[]>;
	Tab: {
		minifyURL: (url: string) => string;
	};
	content: {
		getSetupTabUl: () => HTMLUListElement;
		performActionOnTabs: (
			action: string,
			redirectElement: { url: string },
		) => void;
	};
	favouriteManager: {
		FAVOURITE_BUTTON_ID: string;
		showFavouriteButton: () => Promise<void>;
	};
	generator: {
		MODAL_ID: string;
		sldsConfirm: (options: {
			title: string;
			body: string;
			confirmLabel: string;
			cancelLabel: string;
			closeLabel: string;
		}) => Promise<boolean>;
		generateSldsPromptModal: (options: {
			modalTitle: string;
			bodyText: string;
			confirmButtonLabel: string;
			cancelButtonLabel: string;
			closeButtonLabel: string;
		}) => Record<string, HTMLElement>;
		generateTutorialElements: () => Promise<Record<string, HTMLElement>>;
	};
	tabContainer: {
		ensureAllTabsAvailability: () => Promise<Array<{ url: string }>>;
		TabContainer: {
			keyPinnedTabsNo: string;
		};
	};
	manageTabs: {
		handleActionButtonClick: (event: {
			preventDefault: () => void;
			stopPropagation: () => void;
		}) => void;
	};
	sfElements: {
		getCurrentHref: () => string;
	};
	toast: {
		showToast: (message: string, status: string) => void;
	};
};

/**
 * Concrete return type for the local tutorial harness factory.
 */
type Harness = ReturnType<typeof createHarness>;
/**
 * Tutorial UI elements generated by the stubbed modal factory.
 */
type TutorialUi = {
	overlay: HTMLElement;
	messageBox: HTMLElement;
	spinner: HTMLElement;
	segments: HTMLElement;
	confirmBtn: HTMLElement;
	closeBtn: HTMLElement;
	btnsParent: HTMLElement;
};
/**
 * Tutorial prompt UI elements generated by the stubbed prompt modal factory.
 */
type TutorialPromptUi = {
	modalParent: HTMLElement;
	bodyParagraph: HTMLElement;
	saveButton: HTMLElement;
	cancelButton: HTMLElement;
	closeButton: HTMLElement;
};

/**
 * Minimal mutable tutorial surface needed to advance a step in tests.
 */
type TutorialDriver = {
	currentStep: number;
	nextStep: () => Promise<void> | void;
	steps: Array<{
		action?: string;
		onConfirm?: () => void;
	}>;
};

type TutorialStep = {
	action?: string;
	awaitsCustomEvent?: string;
	beginsBlock?: boolean;
	element?: () => HTMLElement | Promise<HTMLElement | null> | null;
	fakeElement?: () => HTMLElement | Promise<HTMLElement | null> | null;
	isEndingStep?: boolean;
	link?: string;
	message?: string;
	onConfirm?: () => void;
	pageUrl?: string;
	redirectElement?: { label: string; url: string };
	shortcut?: string;
	waitFor?: string;
};

/**
 * Polls until a condition becomes true or the timeout expires.
 *
 * @param predicate Condition checked on each poll.
 * @param timeoutMs Maximum time to wait in milliseconds.
 * @return Resolves once the predicate succeeds.
 */
async function waitFor(predicate: () => boolean, timeoutMs = 1000) {
	const startedAt = Date.now();
	while (!predicate()) {
		if (Date.now() - startedAt > timeoutMs) {
			throw new Error("Timed out waiting for test condition");
		}
		await new Promise((resolve) => setTimeout(resolve, 10));
	}
}

type TutorialModule = {
	Tutorial: new () => TutorialDriver & {
		btnsParent: HTMLElement;
		closeBtn: HTMLElement;
		confirmBtn: HTMLElement;
		createOverlay: () => Promise<void>;
		currentStep: number;
		end: (options?: {
			shouldSaveProgress?: boolean;
			stepToSave?: number;
			closedManually?: boolean;
		}) => void;
		executeStep: (step: TutorialStep) => Promise<void>;
		getElementNowOrLater: (
			step: TutorialStep,
			callback: (step: TutorialStep) => void,
		) => Promise<HTMLElement | undefined | null>;
		hideSpinner: () => void;
		highlightElement: (element: HTMLElement) => void;
		initSteps: () => Promise<boolean>;
		isActive: boolean;
		messageBox: HTMLElement;
		nextStep: () => Promise<void> | void;
		persistTutorialProgress: (
			stepNo?: number | string,
			closedManually?: boolean,
		) => Promise<void> | void;
		retryCount: number;
		segments: HTMLElement;
		showConfirm: () => void;
		showMessage: (step: TutorialStep) => Promise<void>;
		showSpinner: () => void;
		spinner: HTMLElement;
		start: (startStep?: number) => Promise<void>;
		steps: TutorialStep[];
		throwConfetti: () => void;
		translator: Translator;
	};
	checkTutorial: (fromPopup?: boolean) => Promise<void>;
};

/**
 * Loads the real tutorial module after replacing its imports with injected test doubles.
 *
 * @param deps Dependency bundle exposed through `globalThis`.
 * @return Loaded tutorial module plus isolated-module cleanup hooks.
 */
async function loadTutorialModule(deps: TutorialDeps) {
	const flattenedDeps = {
		...deps.constants,
		...deps.functions,
		...deps.content,
		...deps.favouriteManager,
		...deps.generator,
		...deps.manageTabs,
		...deps.tabContainer,
		...deps.sfElements,
		...deps.toast,
		Tab: deps.Tab,
		ensureTranslatorAvailability: deps.ensureTranslatorAvailability,
		getTranslations: deps.getTranslations,
	};
	return await loadIsolatedModule<
		TutorialModule,
		typeof flattenedDeps
	>({
		modulePath: TUTORIAL_PATH,
		additionalExports: ["Tutorial"],
		dependencies: flattenedDeps,
		importsToReplace: new Set([
			"/core/constants.js",
			"/core/functions.js",
			"/core/translator.js",
			"/core/tab.js",
			"./content.js",
			"./favourite-manager.js",
			"./generator.js",
			"/core/tabContainer.js",
			"./manageTabs.js",
			"./sf-elements.js",
			"./toast.js",
		]),
	});
}

/**
 * Installs a writable global property for the lifetime of a test.
 *
 * @param name Global property name.
 * @param value Value assigned to the property.
 */
function setGlobal<T>(name: string, value: T) {
	Object.defineProperty(globalThis, name, {
		value,
		configurable: true,
		writable: true,
	});
}

/**
 * Flushes pending timers and waits for Happy DOM async work to settle.
 *
 * @return Resolves after the test environment becomes idle.
 */
async function flush() {
	await new Promise((resolve) => setTimeout(resolve, 0));
	await (globalThis.window as {
		happyDOM?: { waitUntilComplete?: () => Promise<void> };
	}).happyDOM?.waitUntilComplete?.();
}

/**
 * Advances the currently active tutorial step without relying on DOM click wiring.
 *
 * This mirrors the production confirm handler semantics closely enough for the
 * browserless end-to-end test while leaving `tutorial.js` unchanged.
 *
 * @param tutorial Tutorial instance under test.
 * @return Resolves after the triggered step work has settled.
 */
async function advanceCurrentStep(tutorial: TutorialDriver) {
	const step = tutorial.steps[tutorial.currentStep];
	step?.onConfirm?.();
	if (step?.action !== "confirm") {
		await tutorial.nextStep();
	}
	await flush();
}

/**
 * Creates a fresh mock window and temporarily binds it onto `globalThis`.
 *
 * @param url Initial page URL for the simulated browser window.
 * @return Window handle plus a cleanup callback that restores previous globals.
 */
function installDom(url = DEFAULT_URL) {
	return installMockDom(url);
}

/**
 * Builds a reusable browserless harness around the real tutorial module.
 *
 * @param options Initial storage, navigation, and tab state for the tutorial.
 * @return Harness helpers, dependency doubles, and captured side effects.
 */
function createHarness(options: {
	tutorialProgress?: number | null;
	savedTabUrls?: string[];
	url?: string;
	pinnedTabsNo?: number;
} = {}) {
	const dom = installDom(options.url);
	const setupTabUl = globalThis.document.createElement("ul");
	globalThis.document.body.appendChild(setupTabUl);
	const state = {
		savedTabUrls: [
			...(options.savedTabUrls ?? ["SavedOne/home", "SavedTwo/home"]),
		],
		pinnedTabsNo: options.pinnedTabsNo ?? 0,
	};

	const constants = {
		CMD_OPEN_SETTINGS: "cmd-open-settings",
		CXM_UNPIN_TAB: "unpin-tab",
		EXTENSION_GITHUB_LINK: "https://example.test/again-why-salesforce",
		HIDDEN_CLASS: "is-hidden",
		SALESFORCE_SETUP_HOME_MINI: "SetupOneHome/home",
		SETUP_LIGHTNING: "/lightning/setup/",
		TOAST_WARNING: "warning",
		TUTORIAL_EVENT_ACTION_FAVOURITE: "tutorial:actionFavourite:completed",
		TUTORIAL_EVENT_ACTION_UNFAVOURITE:
			"tutorial:actionUnfavourite:completed",
		TUTORIAL_EVENT_CLOSE_MANAGE_TABS: "tutorial:manageTabs:closed",
		TUTORIAL_EVENT_CREATE_MANAGE_TABS_MODAL:
			"tutorial:createManageTabsModal:completed",
		TUTORIAL_EVENT_PIN_TAB: "tutorial:pinTab:completed",
		TUTORIAL_EVENT_REORDERED_TABS_TABLE: "tutorial:tableReorder:completed",
		TUTORIAL_CLOSE_EVENT: "tutorial-progress-close-event",
		TUTORIAL_KEY: "tutorial-progress",
		WHAT_ADD: "add",
		WHAT_GET: "get",
		WHAT_GET_COMMANDS: "get-commands",
		WHAT_SET: "set",
	};
	const records = {
		redirects: [] as string[],
		messages: [] as Array<Record<string, TutorialMessageValue>>,
		toasts: [] as Array<{ message: string; status: string }>,
		latestUi: null as null | TutorialUi,
		latestPrompt: null as null | TutorialPromptUi,
		actionButtonClicks: 0,
	};
	const storage: Record<string, TutorialStorageValue> = {
		[constants.TUTORIAL_KEY]: options.tutorialProgress ?? null,
	};
	let moduleCleanup: (() => void) | null = null;
	const translator: Translator = {
		translate: (key: string) => Promise.resolve(`translated:${key}`),
	};

	/**
	 * Resolves a mocked storage message against the local harness state.
	 *
	 * @param message Simulated background message.
	 * @return Stored value or acknowledgement.
	 */
	function resolveStorageMessage(
		message: Record<string, TutorialMessageValue>,
	) {
		records.messages.push(message);
		switch (message.what) {
			case constants.WHAT_GET:
				if (Array.isArray(message.key)) {
					return Promise.resolve(Object.fromEntries(
						message.key.map((key) => [key, storage[key]]),
					));
				}
				return Promise.resolve(storage[message.key as string]);
			case constants.WHAT_GET_COMMANDS:
				return Promise.resolve([{ shortcut: "Ctrl+Shift+Y" }]);
			case constants.WHAT_SET:
				storage[message.key as string] = message.set;
				return Promise.resolve(true);
			default:
				return Promise.resolve(null);
		}
	}

	/**
	 * Creates one setup tab entry matching the structure expected by the tutorial.
	 *
	 * @param url Minified Salesforce Setup URL stored in the anchor title.
	 * @return List item containing the simulated setup link.
	 */
	function createSetupLink(url: string) {
		const li = globalThis.document.createElement("li");
		const link = globalThis.document.createElement("a");
		link.title = url;
		link.textContent = url;
		li.appendChild(link);
		return li;
	}

	/**
	 * Re-renders the mocked Setup tab list from the harness state.
	 */
	function renderSetupTabs() {
		setupTabUl.innerHTML = "";
		for (const url of state.savedTabUrls) {
			setupTabUl.appendChild(createSetupLink(url));
		}
	}

	/**
	 * Ensures the favourite star exists and is visible to hit-testing code.
	 *
	 * @return Visible favourite button element.
	 */
	function ensureVisibleFavouriteButton() {
		let button = globalThis.document.getElementById(
			"again-why-salesforce-star",
		) as HTMLInputElement | null;
		if (button == null) {
			button = globalThis.document.createElement("input");
			button.id = "again-why-salesforce-star";
			globalThis.document.body.appendChild(button);
		}
		button.getBoundingClientRect = () =>
			({
				width: 24,
				height: 24,
				top: 0,
				left: 0,
				right: 24,
				bottom: 24,
				x: 0,
				y: 0,
				toJSON: () => ({}),
			}) as DOMRect;
		return button;
	}

	/**
	 * Converts the current full URL into the minified Setup path used by the tutorial.
	 *
	 * @return Current Setup path without the origin prefix.
	 */
	function currentMiniUrl() {
		return globalThis.location.href.replace(
			/^https?:\/\/[^/]+\/lightning\/setup\//,
			"",
		);
	}

	/**
	 * Renders page-level fixtures needed for a given mocked Setup page.
	 *
	 * @param miniUrl Minified Setup URL being shown.
	 */
	function renderPage(miniUrl: string) {
		renderSetupTabs();
		const starButton = globalThis.document.getElementById(
			"again-why-salesforce-star",
		);
		if (miniUrl === constants.SALESFORCE_SETUP_HOME_MINI) {
			starButton?.remove();
			return;
		}
		ensureVisibleFavouriteButton();
	}

	/**
	 * Navigates the harness to a mocked Lightning Setup URL.
	 *
	 * @param miniUrl Minified Setup URL to visit.
	 */
	function navigateTo(miniUrl: string) {
		renderPage(miniUrl);
		globalThis.history.pushState(
			{},
			"",
			`${constants.SETUP_LIGHTNING}${miniUrl}`,
		);
	}

	/**
	 * Creates the minimal Manage Tabs modal DOM required by tutorial steps.
	 *
	 * @param rows Number of sortable rows rendered in the modal table.
	 * @return Root modal element.
	 */
	function createManageTabsModal(rows = state.savedTabUrls.length) {
		globalThis.document.getElementById("again-why-salesforce-modal")
			?.remove();
		const modal = globalThis.document.createElement("div");
		modal.id = "again-why-salesforce-modal";
		const table = globalThis.document.createElement("table");
		table.id = "sortable-table";
		const tbody = globalThis.document.createElement("tbody");
		for (let index = 0; index < rows; index++) {
			const row = globalThis.document.createElement("tr");
			const wrapCell = globalThis.document.createElement("td");
			const wrap = globalThis.document.createElement("div");
			wrap.className = "slds-cell-wrap";
			wrap.textContent = `Row ${index + 1}`;
			wrapCell.appendChild(wrap);
			row.appendChild(wrapCell);
			const actionCell = globalThis.document.createElement("td");
			const actionButton = globalThis.document.createElement("button");
			actionButton.dataset.action = constants.CXM_UNPIN_TAB;
			actionCell.appendChild(actionButton);
			row.appendChild(actionCell);
			tbody.appendChild(row);
		}
		table.appendChild(tbody);
		modal.appendChild(table);
		const saveButton = globalThis.document.createElement("button");
		saveButton.id = "again-why-salesforce-modal-save-btn";
		modal.appendChild(saveButton);
		globalThis.document.body.appendChild(modal);
		return modal;
	}

	/**
	 * Updates harness state for a tutorial event and dispatches it on the document.
	 *
	 * @param eventName Tutorial custom event name to emit.
	 */
	function dispatchTutorialEvent(eventName: string) {
		switch (eventName) {
			case constants.TUTORIAL_EVENT_PIN_TAB:
				state.pinnedTabsNo = Math.max(state.pinnedTabsNo, 1);
				break;
			case constants.TUTORIAL_EVENT_ACTION_FAVOURITE: {
				const miniUrl = currentMiniUrl();
				if (!state.savedTabUrls.includes(miniUrl)) {
					state.savedTabUrls.push(miniUrl);
					renderSetupTabs();
				}
				break;
			}
			case constants.TUTORIAL_EVENT_ACTION_UNFAVOURITE: {
				const miniUrl = currentMiniUrl();
				state.savedTabUrls = state.savedTabUrls.filter((url) =>
					url !== miniUrl
				);
				renderSetupTabs();
				break;
			}
		}
		globalThis.document.dispatchEvent(
			new globalThis.CustomEvent(eventName),
		);
	}

	/**
	 * Waits until the visible tutorial message starts with the translated key.
	 *
	 * @param key Translation key expected in the message box.
	 * @return Resolves once the message box shows the requested step.
	 */
	async function waitForMessage(key: string) {
		await waitFor(() =>
			records.latestUi?.segments.textContent?.startsWith(
				`translated:${key}`,
			) === true
		);
	}

	const deps: TutorialDeps = {
		constants,
		functions: {
			performLightningRedirect: (url) => {
				records.redirects.push(url);
				const miniUrl = url.replace(/^\/lightning\/setup\//, "");
				navigateTo(miniUrl);
			},
			sendExtensionMessage: resolveStorageMessage,
			sendExtensionMessages: (messages) =>
				Promise.all(
					messages.map((message) => resolveStorageMessage(message)),
				),
		},
		ensureTranslatorAvailability: () => Promise.resolve(translator),
		getTranslations: async (keys, connector = " ") => {
			const translateSingle = async (key: string) =>
				await Promise.resolve(translator.translate(key));
			if (!Array.isArray(keys)) {
				return translateSingle(keys);
			}
			const translated = await Promise.all(
				keys.map((key) => translateSingle(key)),
			);
			return connector == null ? translated : translated.join(connector);
		},
		Tab: {
			minifyURL: (url) =>
				url.replace(/^https?:\/\/[^/]+\/lightning\/setup\//, ""),
		},
		content: {
			getSetupTabUl: () => setupTabUl,
			performActionOnTabs: (_action, redirectElement) => {
				if (!state.savedTabUrls.includes(redirectElement.url)) {
					state.savedTabUrls.push(redirectElement.url);
				}
				renderSetupTabs();
			},
		},
		favouriteManager: {
			FAVOURITE_BUTTON_ID: "again-why-salesforce-star",
			showFavouriteButton: () => {
				ensureVisibleFavouriteButton();
				return Promise.resolve();
			},
		},
		generator: {
			MODAL_ID: "again-why-salesforce-modal",
			sldsConfirm: ({
				title,
				body,
				confirmLabel,
				cancelLabel,
				closeLabel,
			}) => {
				const {
					modalParent,
					saveButton,
					cancelButton,
					closeButton,
				} = deps.generator.generateSldsPromptModal({
					modalTitle: title,
					bodyText: body,
					confirmButtonLabel: confirmLabel,
					cancelButtonLabel: cancelLabel,
					closeButtonLabel: closeLabel,
				});
				modalParent.id = "again-why-salesforce-confirm-modal";
				globalThis.document.body.appendChild(modalParent);
				records.latestPrompt = {
					modalParent,
					bodyParagraph: modalParent.querySelector(
						"p",
					) as HTMLElement,
					saveButton,
					cancelButton,
					closeButton,
				};
				saveButton.focus();
				return new Promise((resolve) => {
					let isResolved = false;
					/**
					 * Resolves the mocked prompt only once.
					 *
					 * @param value User choice.
					 * @return {void}
					 */
					function finish(value: boolean) {
						if (isResolved) {
							return;
						}
						isResolved = true;
						modalParent.remove();
						resolve(value);
					}
					saveButton.addEventListener("click", (event) => {
						event.preventDefault();
						finish(true);
					});
					cancelButton.addEventListener("click", (event) => {
						event.preventDefault();
						finish(false);
					});
					closeButton.addEventListener("click", () => finish(false));
				});
			},
			generateSldsPromptModal: ({
				modalTitle,
				bodyText,
				confirmButtonLabel,
				cancelButtonLabel,
				closeButtonLabel,
			}) => {
				const modalParent = globalThis.document.createElement("div");
				modalParent.id = "again-why-salesforce-modal";
				const heading = globalThis.document.createElement("h2");
				heading.textContent = modalTitle;
				modalParent.appendChild(heading);
				const bodyParagraph = globalThis.document.createElement("p");
				bodyParagraph.textContent = bodyText;
				modalParent.appendChild(bodyParagraph);
				const saveButton = globalThis.document.createElement("button");
				saveButton.textContent = confirmButtonLabel;
				modalParent.appendChild(saveButton);
				const cancelButton = globalThis.document.createElement(
					"button",
				);
				cancelButton.textContent = cancelButtonLabel;
				modalParent.appendChild(cancelButton);
				const closeButton = globalThis.document.createElement("button");
				closeButton.textContent = closeButtonLabel;
				modalParent.appendChild(closeButton);
				records.latestPrompt = {
					modalParent,
					bodyParagraph,
					saveButton,
					cancelButton,
					closeButton,
				};
				return {
					modalParent,
					bodyParagraph,
					saveButton,
					cancelButton,
					closeButton,
				};
			},
			generateTutorialElements: () => {
				const overlay = globalThis.document.createElement("div");
				const messageBox = globalThis.document.createElement("div");
				messageBox.className = "tut-v7";
				const segments = globalThis.document.createElement("div");
				const btnsParent = globalThis.document.createElement("div");
				btnsParent.classList.add(constants.HIDDEN_CLASS);
				const confirmBtn = globalThis.document.createElement("button");
				confirmBtn.textContent = "translated:confirm";
				const closeBtn = globalThis.document.createElement("button");
				closeBtn.textContent = "translated:close";
				btnsParent.appendChild(confirmBtn);
				btnsParent.appendChild(closeBtn);
				messageBox.appendChild(segments);
				messageBox.appendChild(btnsParent);
				const spinner = globalThis.document.createElement("div");
				spinner.classList.add(constants.HIDDEN_CLASS);
				const ui = {
					overlay,
					messageBox,
					spinner,
					segments,
					confirmBtn,
					closeBtn,
					btnsParent,
				};
				records.latestUi = ui;
				return Promise.resolve(ui);
			},
		},
		tabContainer: {
			ensureAllTabsAvailability: () => {
				const allTabs = state.savedTabUrls.map((url) => ({ url }));
				(allTabs as Array<{ url: string }> & Record<string, number>)[
					"pinnedTabsNo"
				] = state.pinnedTabsNo;
				return Promise.resolve(allTabs);
			},
			TabContainer: {
				keyPinnedTabsNo: "pinnedTabsNo",
			},
		},
		manageTabs: {
			handleActionButtonClick: (event: {
				preventDefault: () => void;
				stopPropagation: () => void;
			}) => {
				event.preventDefault();
				event.stopPropagation();
				records.actionButtonClicks++;
			},
		},
		sfElements: {
			getCurrentHref: () => globalThis.location.href,
		},
		toast: {
			showToast: (message, status) => {
				records.toasts.push({ message, status });
			},
		},
	};

	renderPage(constants.SALESFORCE_SETUP_HOME_MINI);

	return {
		constants,
		deps,
		dom,
		records,
		state,
		setupTabUl,
		storage,
		translator,
		createManageTabsModal,
		dispatchTutorialEvent,
		async load() {
			const loadedModule = await loadTutorialModule(deps);
			moduleCleanup = loadedModule.cleanup;
			return loadedModule.module;
		},
		navigateTo,
		waitForMessage,
		cleanup() {
			moduleCleanup?.();
			dom.cleanup();
		},
	};
}

Deno.test(
	"checkTutorial starts the tutorial without a browser",
	async () => {
		const harness = createHarness({ tutorialProgress: null });
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial();
			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.saveButton.click();
			await checkPromise;
			await harness.waitForMessage("tutorial_restart");

			assertEquals(harness.records.redirects, [
				"/lightning/setup/SetupOneHome/home",
			]);
			assertExists(globalThis.document.querySelector(".tut-v7"));
			assertEquals(
				harness.records.latestUi?.segments.textContent,
				"translated:tutorial_restart",
			);
			assertEquals(harness.storage["tutorial-progress"], 0);
			assert(
				harness.records.messages.some((message) =>
					message.what === "get-commands"
				),
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test("executeStep advances on tutorial custom events", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.translator = harness.translator;
		await tutorial.createOverlay();

		const highlighted = globalThis.document.createElement("div");
		globalThis.document.body.appendChild(highlighted);

		let nextStepCalls = 0;
		tutorial.nextStep = () => {
			nextStepCalls++;
		};

		await tutorial.executeStep({
			message: "tutorial_add_favourite",
			element: () => highlighted,
			action: "highlight",
			waitFor: "event",
			awaitsCustomEvent:
				harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
		});

		assert(highlighted.classList.contains("awsf-tutorial-highlight"));
		assert(
			tutorial.btnsParent.classList.contains(
				harness.constants.HIDDEN_CLASS,
			),
		);

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
		);

		assertEquals(nextStepCalls, 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test(
	"executeStep listens for Lightning navigation without a browser",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			tutorial.translator = harness.translator;
			await tutorial.createOverlay();

			const target = globalThis.document.createElement("div");
			globalThis.document.body.appendChild(target);

			let nextStepCalls = 0;
			tutorial.nextStep = () => {
				nextStepCalls++;
			};

			await tutorial.executeStep({
				message: "tutorial_click_highlighted_tab",
				element: () => target,
				action: "highlight",
				waitFor: "redirect",
			});

			assert(target.classList.contains("awsf-tutorial-highlight"));
			assert(
				tutorial.btnsParent.classList.contains(
					harness.constants.HIDDEN_CLASS,
				),
			);

			harness.navigateTo(
				"ObjectManager/Account/FieldsAndRelationships/view",
			);
			await flush();

			assertEquals(nextStepCalls, 1);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"tutorial runs end to end and persists completion without a browser",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			await tutorial.start();
			await harness.waitForMessage("tutorial_restart");
			assertEquals(tutorial.currentStep, 0);
			assertEquals(harness.storage["tutorial-progress"], 0);

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_favourite_tabs");

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_click_highlighted_tab");

			harness.navigateTo(
				"ObjectManager/Account/FieldsAndRelationships/view",
			);
			await harness.waitForMessage("tutorial_remove_favourite");

			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_ACTION_UNFAVOURITE,
			);
			await harness.waitForMessage("tutorial_redirect_account");

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_add_favourite");

			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
			);
			await harness.waitForMessage("tutorial_pin_tab");

			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_PIN_TAB,
			);
			await harness.waitForMessage("tutorial_pinned_tab");

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_manage_tabs");

			harness.createManageTabsModal();
			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_CREATE_MANAGE_TABS_MODAL,
			);
			await harness.waitForMessage("tutorial_manage_tabs_link");

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_drag_flows");

			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_REORDERED_TABS_TABLE,
			);
			await harness.waitForMessage("tutorial_pinned_explanation");

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_save_modal");

			harness.dispatchTutorialEvent(
				harness.constants.TUTORIAL_EVENT_CLOSE_MANAGE_TABS,
			);
			await harness.waitForMessage("tutorial_keyboard_shortcut");
			assert(
				harness.records.latestUi?.segments.textContent?.includes(
					"Shortcut: Ctrl+Shift+Y",
				),
			);

			await advanceCurrentStep(tutorial);
			await harness.waitForMessage("tutorial_end");
			assertEquals(
				harness.records.latestUi?.closeBtn.textContent,
				"translated:close",
			);
			assertEquals(
				harness.records.latestUi?.confirmBtn.parentElement,
				null,
			);

			await advanceCurrentStep(tutorial);
			await waitFor(() => !tutorial.isActive);

			assertEquals(
				harness.storage["tutorial-progress"],
				tutorial.steps.length,
			);
			assertEquals(globalThis.document.querySelector(".tut-v7"), null);
			assert(
				harness.records.redirects.includes(
					"/lightning/setup/PermSets/home",
				),
			);
			assertEquals(harness.state.pinnedTabsNo, 1);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial resumes from stored progress without a browser",
	async () => {
		const harness = createHarness({ tutorialProgress: 6 });
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial();
			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.saveButton.click();
			await checkPromise;
			await harness.waitForMessage("tutorial_add_favourite");

			assertEquals(harness.records.redirects, [
				"/lightning/setup/ObjectManager/Account/FieldsAndRelationships/view",
			]);
			assertEquals(harness.storage["tutorial-progress"], 5);
			assert(
				harness.records.latestUi?.segments.textContent?.includes(
					"translated:tutorial_add_favourite",
				),
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"executeStep resets to the nearest starting block when a required element is missing",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			tutorial.translator = harness.translator;
			await tutorial.createOverlay();
			tutorial.steps = [
				{ message: "block_zero", beginsBlock: true },
				{ message: "inside_zero" },
				{ message: "block_two", beginsBlock: true },
				{ message: "inside_two" },
				{ message: "current_step" },
			];
			tutorial.currentStep = 4;

			let restartFromStep: number | null = null;
			tutorial.nextStep = () => {
				tutorial.currentStep++;
				restartFromStep = tutorial.currentStep;
			};

			await tutorial.executeStep({
				message: "missing_element_step",
				element: () => null,
			});

			assertEquals(harness.records.toasts, [{
				message: "tutorial_step_was_missed",
				status: "warning",
			}]);
			assertEquals(restartFromStep, 2);
			assertEquals(tutorial.currentStep, 2);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"initSteps returns false and shows a toast when no redirect links are available",
	async () => {
		const harness = createHarness({
			savedTabUrls: ALL_USABLE_PAGE_URLS,
		});
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();

			const initialized = await tutorial.initSteps();

			assertEquals(initialized, false);
			assertEquals(harness.records.toasts, [{
				message: "tutorial_export_and_reset_for_tutorial",
				status: "warning",
			}]);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"persistTutorialProgress validates input and clamps the last step to completion",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			tutorial.steps = [{}, {}, {}];
			tutorial.currentStep = 2;

			assertThrows(
				() => tutorial.persistTutorialProgress("bad"),
				TypeError,
				"stepNo should be a number",
			);

			await tutorial.persistTutorialProgress();
			assertEquals(harness.storage["tutorial-progress"], 3);
			assertEquals(
				harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT],
				"auto",
			);

			await tutorial.persistTutorialProgress(1, true);
			assertEquals(harness.storage["tutorial-progress"], 1);
			assertEquals(
				harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT],
				"user",
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"showMessage appends link and shortcut only when they are not already present",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			await tutorial.createOverlay();
			harness.translator.translate = (key: string) => {
				if (key === "already_complete") {
					return "Message with https://docs.test and Shortcut: Alt+K";
				}
				return "Base message";
			};

			tutorial.showSpinner();
			await tutorial.showMessage({
				message: "base",
				link: "https://docs.test",
				shortcut: "Alt+K",
			});
			assertEquals(
				tutorial.segments.textContent,
				"Base message\n\nhttps://docs.test\n\nShortcut: Alt+K",
			);
			assert(
				tutorial.spinner.classList.contains(
					harness.constants.HIDDEN_CLASS,
				),
			);

			await tutorial.showMessage({
				message: "already_complete",
				link: "https://docs.test",
				shortcut: "Alt+K",
			});
			assertEquals(
				tutorial.segments.textContent,
				"Message with https://docs.test and Shortcut: Alt+K",
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"getElementNowOrLater creates a fake element after enough retries",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			const fakeEl = globalThis.document.createElement("div");
			let callbackCalls = 0;
			tutorial.retryCount = 5;

			const result = await tutorial.getElementNowOrLater({
				element: () => null,
				fakeElement: () => fakeEl,
			}, () => {
				callbackCalls++;
			});

			assertEquals(result, fakeEl);
			assertEquals(tutorial.retryCount, 6);
			assertEquals(callbackCalls, 0);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"getElementNowOrLater schedules a retry when the element is still missing",
	async () => {
		const harness = createHarness();
		const originalSetTimeout = globalThis.setTimeout;
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			const scheduled = [] as Array<
				{ delay: number; callback: () => void }
			>;
			setGlobal(
				"setTimeout",
				((callback: () => void, delay: number) => {
					scheduled.push({ delay, callback });
					return 1;
				}) as typeof setTimeout,
			);

			let callbackCalls = 0;
			const step = {
				element: () => null,
				fakeElement: () => null,
			};

			const result = await tutorial.getElementNowOrLater(
				step,
				(receivedStep) => {
					assertEquals(receivedStep, step);
					callbackCalls++;
				},
			);

			assertEquals(result, undefined);
			assertEquals(tutorial.retryCount, 1);
			assertEquals(scheduled.length, 1);
			assertEquals(scheduled[0].delay, 1000);

			scheduled[0].callback();
			assertEquals(callbackCalls, 1);
		} finally {
			setGlobal("setTimeout", originalSetTimeout);
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"end(false) cleans up the UI without overwriting stored progress",
	async () => {
		const harness = createHarness({ tutorialProgress: 4 });
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			tutorial.steps = [{}, {}, {}];
			tutorial.isActive = true;
			await tutorial.createOverlay();
			const highlighted = globalThis.document.createElement("div");
			globalThis.document.body.appendChild(highlighted);
			tutorial.highlightElement(highlighted);

			tutorial.end({ shouldSaveProgress: false });

			assertEquals(tutorial.isActive, false);
			assertEquals(globalThis.document.querySelector(".tut-v7"), null);
			assert(!highlighted.classList.contains("awsf-tutorial-highlight"));
			assertEquals(harness.storage["tutorial-progress"], 4);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial marks the tutorial completed when the user declines the first prompt",
	async () => {
		const harness = createHarness({ tutorialProgress: null });
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial();
			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.cancelButton.click();
			await checkPromise;
			await waitFor(() => harness.storage["tutorial-progress"] != null);

			assertEquals(harness.storage["tutorial-progress"], 15);
			assertEquals(harness.records.redirects, []);
			assertEquals(globalThis.document.querySelector(".tut-v7"), null);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial marks the tutorial completed when the user declines to continue",
	async () => {
		const harness = createHarness({ tutorialProgress: 3 });
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial();
			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.cancelButton.click();
			await checkPromise;
			await waitFor(() => harness.storage["tutorial-progress"] === 15);

			assertEquals(harness.records.redirects, []);
			assertEquals(globalThis.document.querySelector(".tut-v7"), null);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"nextStep configures the ending step and triggers confetti",
	async () => {
		const harness = createHarness();
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();
			tutorial.translator = harness.translator;
			await tutorial.createOverlay();
			tutorial.steps = [{
				message: "tutorial_end",
				beginsBlock: true,
				isEndingStep: true,
				waitFor: "confirm",
			}];
			tutorial.currentStep = -1;

			let confettiCalls = 0;
			tutorial.throwConfetti = () => {
				confettiCalls++;
			};

			await tutorial.nextStep();

			assertEquals(tutorial.currentStep, 0);
			assertEquals(tutorial.closeBtn.textContent, "translated:close");
			assertEquals(tutorial.confirmBtn.parentElement, null);
			assertEquals(confettiCalls, 1);
			assertEquals(harness.storage["tutorial-progress"], 1);
			assertEquals(
				harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT],
				"auto",
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"tutorial initSteps covers fallback redirect elements and fake-element helpers",
	async () => {
		const harness = createHarness({
			savedTabUrls: ALL_USABLE_PAGE_URLS.slice(2),
		});
		try {
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();

			assertEquals(await tutorial.initSteps(), true);
			assertEquals(
				tutorial.steps[4]?.redirectElement?.url,
				"ObjectManager/Case/FieldsAndRelationships/view",
			);

			harness.state.savedTabUrls = [
				"ObjectManager/Account/FieldsAndRelationships/view",
			];
			harness.navigateTo(
				"ObjectManager/Account/FieldsAndRelationships/view",
			);
			const fallbackTitle =
				"ObjectManager/Account/FieldsAndRelationships/view";
			const originalQuerySelector = harness.setupTabUl.querySelector.bind(
				harness.setupTabUl,
			);
			const matchingLink = harness.setupTabUl.firstElementChild
				?.firstElementChild as HTMLAnchorElement;
			let selectorCalls = 0;
			harness.setupTabUl.querySelector = ((selector: string) => {
				selectorCalls++;
				if (selectorCalls === 1) {
					return null;
				}
				if (selector === `a[title="${fallbackTitle}"]`) {
					return matchingLink;
				}
				return originalQuerySelector(selector);
			}) as typeof harness.setupTabUl.querySelector;
			tutorial.currentStep = 2;
			const fallbackSetupLink = await tutorial.steps[2]?.element?.();
			assertEquals(
				(fallbackSetupLink as HTMLAnchorElement | null)?.title,
				fallbackTitle,
			);
			harness.setupTabUl.querySelector = originalQuerySelector;

			harness.state.savedTabUrls = [];
			harness.navigateTo(harness.constants.SALESFORCE_SETUP_HOME_MINI);
			tutorial.currentStep = 2;
			const generatedSetupLink = await tutorial.steps[2]?.fakeElement?.();
			assertEquals(
				(generatedSetupLink as HTMLAnchorElement | null)?.title,
				"ObjectManager/Account/FieldsAndRelationships/view",
			);

			harness.navigateTo(
				"ObjectManager/Account/FieldsAndRelationships/view",
			);
			tutorial.currentStep = 3;
			const shownStar = await tutorial.steps[3]?.fakeElement?.();
			assertExists(shownStar);

			harness.navigateTo(
				"ObjectManager/Case/FieldsAndRelationships/view",
			);
			tutorial.currentStep = 5;
			const secondShownStar = await tutorial.steps[5]?.fakeElement?.();
			assertExists(secondShownStar);

			harness.state.savedTabUrls = [];
			harness.navigateTo(
				"ObjectManager/Case/FieldsAndRelationships/view",
			);
			tutorial.currentStep = 6;
			const generatedPinnedTab = await tutorial.steps[6]?.fakeElement?.();
			assertEquals(
				(generatedPinnedTab as HTMLLIElement | null)?.tagName,
				"LI",
			);

			tutorial.currentStep = 7;
			const generatedPinnedLink = await tutorial.steps[7]
				?.fakeElement?.();
			assertEquals(
				(generatedPinnedLink as HTMLAnchorElement | null)?.title,
				"ObjectManager/Case/FieldsAndRelationships/view",
			);

			harness.createManageTabsModal(harness.state.savedTabUrls.length);
			harness.state.pinnedTabsNo = harness.state.savedTabUrls.length;
			const dragElement = await tutorial.steps[10]?.element?.();
			assertExists(dragElement);
			assertEquals(harness.records.actionButtonClicks > 0, true);

			harness.state.savedTabUrls = [
				"ObjectManager/Case/FieldsAndRelationships/view",
				"ObjectManager/Lead/FieldsAndRelationships/view",
				"ObjectManager/Task/FieldsAndRelationships/view",
			];
			harness.createManageTabsModal(3);
			harness.state.pinnedTabsNo = 3;
			const fallbackDragElement = await tutorial.steps[10]?.element?.();
			assertExists(fallbackDragElement);
			assertEquals(harness.records.actionButtonClicks >= 3, true);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"tutorial fake favourite lookup can return undefined when no visible star exists",
	async () => {
		const harness = createHarness();
		try {
			harness.deps.favouriteManager.showFavouriteButton = () =>
				Promise.resolve();
			const tutorialModule = await harness.load();
			const tutorial = new tutorialModule.Tutorial();

			assertEquals(await tutorial.initSteps(), true);
			globalThis.history.pushState(
				{},
				"",
				`${harness.constants.SETUP_LIGHTNING}ObjectManager/Account/FieldsAndRelationships/view`,
			);
			tutorial.currentStep = 3;

			assertEquals(await tutorial.steps[3]?.fakeElement?.(), undefined);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"tutorial overlay handlers cover close button, escape, default event waiters, and popstate redirects",
	async () => {
		const harness = createHarness();
		const originalMutationObserver = globalThis.MutationObserver;
		try {
			const tutorialModule = await harness.load();

			const closeTutorial = new tutorialModule.Tutorial();
			closeTutorial.translator = harness.translator;
			closeTutorial.steps = [{ message: "tutorial_restart" }];
			closeTutorial.currentStep = 0;
			let savedStep: number | null = null;
			let closeWasManual: boolean | null = null;
			closeTutorial.persistTutorialProgress = (
				stepNo?: number | string,
				closedManually?: boolean,
			) => {
				savedStep = Number(stepNo);
				closeWasManual = closedManually ?? false;
			};
			await closeTutorial.createOverlay();
			closeTutorial.closeBtn.click();
			assertEquals(savedStep, 1);
			assertEquals(closeWasManual, true);

			const escapeTutorial = new tutorialModule.Tutorial();
			escapeTutorial.translator = harness.translator;
			escapeTutorial.steps = [{ message: "tutorial_restart" }];
			escapeTutorial.currentStep = 0;
			let escapeSavedStep: number | null = null;
			let escapeWasManual: boolean | null = null;
			escapeTutorial.persistTutorialProgress = (
				stepNo?: number | string,
				closedManually?: boolean,
			) => {
				escapeSavedStep = Number(stepNo);
				escapeWasManual = closedManually ?? false;
			};
			await escapeTutorial.createOverlay();
			const escapeEvent = new Event("keydown");
			Object.defineProperty(escapeEvent, "key", { value: "Escape" });
			document.dispatchEvent(escapeEvent);
			assertEquals(escapeSavedStep, 0);
			assertEquals(escapeWasManual, false);

			const clickTutorial = new tutorialModule.Tutorial();
			clickTutorial.translator = harness.translator;
			await clickTutorial.createOverlay();
			let nextStepCalls = 0;
			clickTutorial.nextStep = () => {
				nextStepCalls++;
			};
			await clickTutorial.executeStep({
				message: "tutorial_manage_tabs",
				waitFor: "event",
			});
			document.dispatchEvent(new Event("click"));
			assertEquals(nextStepCalls, 1);

			const popstateTutorial = new tutorialModule.Tutorial();
			popstateTutorial.translator = harness.translator;
			await popstateTutorial.createOverlay();
			let popstateNextSteps = 0;
			popstateTutorial.nextStep = () => {
				popstateNextSteps++;
			};
			await popstateTutorial.executeStep({
				action: "highlight",
				message: "tutorial_redirect_account",
				waitFor: "redirect",
			});
			globalThis.dispatchEvent(new Event("popstate"));
			assertEquals(popstateNextSteps, 1);

			const observerTutorial = new tutorialModule.Tutorial();
			observerTutorial.translator = harness.translator;
			let triggerMutationObserver = () => {};
			setGlobal(
				"MutationObserver",
				class {
					constructor(callback: () => void) {
						triggerMutationObserver = callback;
					}
					disconnect() {}
					observe() {}
				},
			);
			await observerTutorial.createOverlay();
			let observerNextSteps = 0;
			observerTutorial.nextStep = () => {
				observerNextSteps++;
			};
			await observerTutorial.executeStep({
				action: "highlight",
				message: "tutorial_redirect_account",
				waitFor: "redirect",
			});
			globalThis.history.pushState(
				{},
				"",
				"/lightning/setup/ObjectManager/Case/FieldsAndRelationships/view",
			);
			triggerMutationObserver();
			assertEquals(observerNextSteps, 2);
			setGlobal("MutationObserver", originalMutationObserver);

			const confirmTutorial = new tutorialModule.Tutorial();
			confirmTutorial.translator = harness.translator;
			await confirmTutorial.createOverlay();
			let confirmCalls = 0;
			let confirmNextSteps = 0;
			confirmTutorial.currentStep = 0;
			confirmTutorial.steps = [{
				action: "highlight",
				message: "tutorial_restart",
				onConfirm: () => {
					confirmCalls++;
				},
			}];
			confirmTutorial.nextStep = () => {
				confirmNextSteps++;
			};
			confirmTutorial.showConfirm();
			confirmTutorial.messageBox.dispatchEvent(new Event("click"));
			assertEquals(confirmCalls, 1);
			assertEquals(confirmNextSteps, 1);
		} finally {
			setGlobal("MutationObserver", originalMutationObserver);
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"tutorial start branches cover failed initialization, invalid start steps, manual start, and failed resume",
	async () => {
		const harness = createHarness({ tutorialProgress: 2 });
		const originalConsoleError = console.error;
		const errorCalls: string[] = [];
		console.error = (message?: string | number | boolean | null) => {
			errorCalls.push(String(message));
		};

		try {
			const tutorialModule = await harness.load();

			const failedStartTutorial = new tutorialModule.Tutorial();
			failedStartTutorial.initSteps = () => Promise.resolve(false);
			await assertRejects(
				() => failedStartTutorial.start(),
				Error,
				"error_tutorial_not_initialized",
			);

			const invalidStartTutorial = new tutorialModule.Tutorial();
			invalidStartTutorial.steps = [{
				message: "tutorial_restart",
				pageUrl: harness.constants.SALESFORCE_SETUP_HOME_MINI,
			}];
			invalidStartTutorial.createOverlay = () => Promise.resolve();
			invalidStartTutorial.nextStep = () => {};
			await invalidStartTutorial.start(999);
			assertEquals(invalidStartTutorial.currentStep, -1);

			const activeTutorial = new tutorialModule.Tutorial();
			activeTutorial.isActive = true;
			let activeOverlayCalls = 0;
			activeTutorial.createOverlay = () => {
				activeOverlayCalls++;
				return Promise.resolve();
			};
			await activeTutorial.start();
			assertEquals(activeOverlayCalls, 0);

			const popupStartPromise = tutorialModule.checkTutorial(true);
			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.cancelButton.click();
			await popupStartPromise;
			await harness.waitForMessage("tutorial_restart");
			assertEquals(
				harness.records.latestUi?.segments.textContent?.startsWith(
					"translated:tutorial_restart",
				) === true,
				true,
			);

			tutorialModule.Tutorial.prototype.initSteps = () =>
				Promise.resolve(false);
			await assertRejects(
				() => tutorialModule.checkTutorial(),
				Error,
				"error_tutorial_not_initialized",
			);
		} finally {
			console.error = originalConsoleError;
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial does not prompt again after a manual close outside the popup",
	async () => {
		const harness = createHarness({ tutorialProgress: 3 });
		harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT] = "user";
		try {
			const tutorialModule = await harness.load();

			await tutorialModule.checkTutorial();

			assertEquals(harness.records.latestPrompt, null);
			assertEquals(harness.records.redirects, []);
			assertEquals(globalThis.document.querySelector(".tut-v7"), null);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial from the popup still prompts after a manual close and can continue",
	async () => {
		const harness = createHarness({ tutorialProgress: 3 });
		harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT] = "user";
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial(true);

			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.saveButton.click();
			await checkPromise;
			await harness.waitForMessage("tutorial_click_highlighted_tab");

			assertEquals(
				harness.records.latestUi?.segments.textContent?.startsWith(
					"translated:tutorial_click_highlighted_tab",
				) === true,
				true,
			);
			assertEquals(
				harness.records.redirects.includes(
					"/lightning/setup/SetupOneHome/home",
				),
				true,
			);
			assertEquals(harness.storage["tutorial-progress"], 2);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);

Deno.test(
	"checkTutorial from the popup restarts from the beginning when the user declines to continue",
	async () => {
		const harness = createHarness({ tutorialProgress: 3 });
		harness.storage[harness.constants.TUTORIAL_CLOSE_EVENT] = "user";
		try {
			const tutorialModule = await harness.load();
			const checkPromise = tutorialModule.checkTutorial(true);

			await waitFor(() => harness.records.latestPrompt != null);
			harness.records.latestPrompt?.cancelButton.click();
			await checkPromise;
			await harness.waitForMessage("tutorial_restart");

			assertEquals(
				harness.records.latestUi?.segments.textContent?.startsWith(
					"translated:tutorial_restart",
				) === true,
				true,
			);
			assertEquals(
				harness.records.redirects,
				[],
			);
		} finally {
			await flush();
			harness.cleanup();
		}
	},
);
