name: Bug report
description: Create a report to help us improve
title: "Bug when ..."
labels: [bug]
assignees: [Astisme]

body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ I am using the **latest version of Again, Why Salesforce**.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      render: block
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      render: block
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      render: block
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      render: block

  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. iOS

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: chrome, edge, safari, firefox, other

  - type: input
    id: version
    attributes:
      label: Version
      description: e.g. 2.0.2

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      render: block

  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false
