import {
	assert,
	assertEquals,
	assertExists,
	assertThrows,
} from "@std/testing/asserts";
import { Window } from "happydom";

/**
 * Filesystem path to the tutorial module under test.
 */
const TUTORIAL_PATH = new URL("../../src/salesforce/tutorial.js", import.meta.url);
/**
 * Baseline Salesforce Setup URL used to initialize the DOM harness.
 */
const DEFAULT_URL =
	"https://acme.my.salesforce-setup.com/lightning/setup/SetupOneHome/home";
/**
 * Every fallback tutorial page supported by the production module.
 */
const ALL_USABLE_PAGE_URLS = [
	"ObjectManager/Account/FieldsAndRelationships/view",
	"ObjectManager/Case/FieldsAndRelationships/view",
	"ObjectManager/Contact/FieldsAndRelationships/view",
	"ObjectManager/Opportunity/FieldsAndRelationships/view",
	"ObjectManager/Lead/FieldsAndRelationships/view",
	"ObjectManager/Task/FieldsAndRelationships/view",
	"ObjectManager/Campaign/FieldsAndRelationships/view",
	"ObjectManager/Product2/FieldsAndRelationships/view",
	"ObjectManager/Pricebook2/FieldsAndRelationships/view",
	"ObjectManager/Asset/FieldsAndRelationships/view",
	"PermSets/home",
	"OrgLoginHistory/home",
	"SecuritySession/home",
	"SecurityEvents/home",
	"SecuritySharing/home",
	"FieldAccessibility/home",
	"CommunicationTemplatesEmail/home",
	"ReportUI/home",
	"ConnectedApplication/home",
	"CompanyProfileInfo/home",
];

/**
 * Minimal translation service surface required by the tutorial.
 */
type Translator = {
	translate: (key: string) => Promise<string>;
};

/**
 * Dependency bundle injected into the tutorial module for browserless tests.
 */
type TutorialDeps = {
	constants: Record<string, string>;
	functions: {
		performLightningRedirect: (url: string) => void;
		sendExtensionMessage: (message: Record<string, unknown>) => Promise<unknown>;
	};
	ensureTranslatorAvailability: () => Promise<Translator>;
	Tab: {
		minifyURL: (url: string) => string;
	};
	content: {
		getCurrentHref: () => string;
		getSetupTabUl: () => HTMLUListElement;
		performActionOnTabs: (
			action: string,
			redirectElement: { url: string },
		) => void;
		showToast: (message: string, status: string) => void;
	};
	favouriteManager: {
		FAVOURITE_BUTTON_ID: string;
		showFavouriteButton: () => Promise<void>;
	};
	generator: {
		MODAL_ID: string;
		generateTutorialElements: () => Promise<Record<string, HTMLElement>>;
	};
	tabContainer: {
		ensureAllTabsAvailability: () => Promise<Array<{ url: string }>>;
		TabContainer: {
			keyPinnedTabsNo: string;
		};
	};
	manageTabs: {
		handleActionButtonClick: () => void;
	};
};

/**
 * Concrete return type for the local tutorial harness factory.
 */
type Harness = ReturnType<typeof createHarness>;
/**
 * Tutorial UI elements generated by the stubbed modal factory.
 */
type TutorialUi = {
	overlay: HTMLElement;
	messageBox: HTMLElement;
	spinner: HTMLElement;
	segments: HTMLElement;
	confirmBtn: HTMLElement;
	btnsParent: HTMLElement;
};

/**
 * Minimal mutable tutorial surface needed to advance a step in tests.
 */
type TutorialDriver = {
	currentStep: number;
	nextStep: () => Promise<void> | void;
	steps: Array<{
		action?: string;
		onConfirm?: () => void;
	}>;
};

/**
 * Polls until a condition becomes true or the timeout expires.
 *
 * @param predicate Condition checked on each poll.
 * @param timeoutMs Maximum time to wait in milliseconds.
 * @return Resolves once the predicate succeeds.
 */
async function waitFor(predicate: () => boolean, timeoutMs = 1000) {
	const startedAt = Date.now();
	while (!predicate()) {
		if (Date.now() - startedAt > timeoutMs) {
			throw new Error("Timed out waiting for test condition");
		}
		await new Promise((resolve) => setTimeout(resolve, 10));
	}
}

/**
 * Removes one static import from the tutorial source so the test can inject a stub.
 *
 * @param source Tutorial source code.
 * @param fileName Import specifier to remove.
 * @return Source code without the matching import statement.
 */
function stripImport(source: string, fileName: string) {
	return source.replace(
		new RegExp(
			String.raw`import[\s\S]*?from\s*"${fileName.replaceAll("/", "\\/")}";\n`,
		),
		"",
	);
}

/**
 * Loads the real tutorial module after replacing its imports with injected test doubles.
 *
 * @param deps Dependency bundle exposed through `globalThis`.
 * @return Imported tutorial module plus the test-only `Tutorial` export.
 */
async function loadTutorialModule(deps: TutorialDeps) {
	let source = await Deno.readTextFile(TUTORIAL_PATH);
	source = source.replace(`"use strict";\n`, "");
	for (const fileName of [
		"/constants.js",
		"/functions.js",
		"/translator.js",
		"/tab.js",
		"./content.js",
		"./favourite-manager.js",
		"./generator.js",
		"../tabContainer.js",
		"./manageTabs.js",
	]) {
		source = stripImport(source, fileName);
	}
	const prelude = `
const __deps = globalThis.__tutorialTestDeps;
const {
	CMD_OPEN_SETTINGS,
	CXM_UNPIN_TAB,
	EXTENSION_GITHUB_LINK,
	HIDDEN_CLASS,
	SALESFORCE_SETUP_HOME_MINI,
	SETUP_LIGHTNING,
	TOAST_WARNING,
	TUTORIAL_EVENT_ACTION_FAVOURITE,
	TUTORIAL_EVENT_ACTION_UNFAVOURITE,
	TUTORIAL_EVENT_CLOSE_MANAGE_TABS,
	TUTORIAL_EVENT_CREATE_MANAGE_TABS_MODAL,
	TUTORIAL_EVENT_PIN_TAB,
	TUTORIAL_EVENT_REORDERED_TABS_TABLE,
	TUTORIAL_KEY,
	WHAT_ADD,
	WHAT_GET,
	WHAT_GET_COMMANDS,
	WHAT_SET,
} = __deps.constants;
const { performLightningRedirect, sendExtensionMessage } = __deps.functions;
const ensureTranslatorAvailability = __deps.ensureTranslatorAvailability;
const Tab = __deps.Tab;
const {
	getCurrentHref,
	getSetupTabUl,
	performActionOnTabs,
	showToast,
} = __deps.content;
const {
	FAVOURITE_BUTTON_ID,
	showFavouriteButton,
} = __deps.favouriteManager;
const { generateTutorialElements, MODAL_ID } = __deps.generator;
const { ensureAllTabsAvailability, TabContainer } = __deps.tabContainer;
const { handleActionButtonClick } = __deps.manageTabs;
`;
	const moduleSource = `${prelude}\n${source}\nexport { Tutorial };\n`;
	const moduleUrl = URL.createObjectURL(
		new Blob([moduleSource], { type: "text/javascript" }),
	);

	try {
		(globalThis as typeof globalThis & { __tutorialTestDeps?: TutorialDeps })
			.__tutorialTestDeps = deps;
		return await import(`${moduleUrl}#${crypto.randomUUID()}`);
	} finally {
		delete (globalThis as typeof globalThis & {
			__tutorialTestDeps?: TutorialDeps;
		}).__tutorialTestDeps;
		URL.revokeObjectURL(moduleUrl);
	}
}

/**
 * Installs a writable global property for the lifetime of a test.
 *
 * @param name Global property name.
 * @param value Value assigned to the property.
 */
function setGlobal(name: string, value: unknown) {
	Object.defineProperty(globalThis, name, {
		value,
		configurable: true,
		writable: true,
	});
}

/**
 * Flushes pending timers and waits for Happy DOM async work to settle.
 *
 * @return Resolves after the test environment becomes idle.
 */
async function flush() {
	await new Promise((resolve) => setTimeout(resolve, 0));
	await (globalThis.window as Window & {
		happyDOM?: { waitUntilComplete?: () => Promise<void> };
	}).happyDOM?.waitUntilComplete?.();
}

/**
 * Advances the currently active tutorial step without relying on DOM click wiring.
 *
 * This mirrors the production confirm handler semantics closely enough for the
 * browserless end-to-end test while leaving `tutorial.js` unchanged.
 *
 * @param tutorial Tutorial instance under test.
 * @return Resolves after the triggered step work has settled.
 */
async function advanceCurrentStep(tutorial: TutorialDriver) {
	const step = tutorial.steps[tutorial.currentStep];
	step?.onConfirm?.();
	if (step?.action !== "confirm") {
		await tutorial.nextStep();
	}
	await flush();
}

/**
 * Creates a fresh Happy DOM window and temporarily binds it onto `globalThis`.
 *
 * @param url Initial page URL for the simulated browser window.
 * @return Window handle plus a cleanup callback that restores previous globals.
 */
function installDom(url = DEFAULT_URL) {
	const window = new Window({ url });
	const previousGlobals = new Map<string, unknown>();
	for (const [name, value] of Object.entries({
		window,
		document: window.document,
		location: window.location,
		history: window.history,
		navigator: window.navigator,
		HTMLElement: window.HTMLElement,
		Element: window.Element,
		Node: window.Node,
		Event: window.Event,
		CustomEvent: window.CustomEvent,
		MutationObserver: window.MutationObserver,
		HTMLCanvasElement: window.HTMLCanvasElement,
		HTMLInputElement: window.HTMLInputElement,
		getComputedStyle: window.getComputedStyle.bind(window),
		requestAnimationFrame: window.requestAnimationFrame.bind(window),
		cancelAnimationFrame: window.cancelAnimationFrame.bind(window),
		performance: window.performance,
	})) {
		previousGlobals.set(name, (globalThis as Record<string, unknown>)[name]);
		setGlobal(name, value);
	}
	globalThis.document.body.innerHTML = "";
	return {
		window,
		cleanup() {
			for (const [name, value] of previousGlobals.entries()) {
				setGlobal(name, value);
			}
		},
	};
}

/**
 * Builds a reusable browserless harness around the real tutorial module.
 *
 * @param options Initial storage, navigation, and tab state for the tutorial.
 * @return Harness helpers, dependency doubles, and captured side effects.
 */
function createHarness(options: {
	tutorialProgress?: number | null;
	savedTabUrls?: string[];
	url?: string;
	pinnedTabsNo?: number;
} = {}) {
	const dom = installDom(options.url);
	const setupTabUl = globalThis.document.createElement("ul");
	globalThis.document.body.appendChild(setupTabUl);
	const state = {
		savedTabUrls: [...(options.savedTabUrls ?? ["SavedOne/home", "SavedTwo/home"])],
		pinnedTabsNo: options.pinnedTabsNo ?? 0,
	};

	const constants = {
		CMD_OPEN_SETTINGS: "cmd-open-settings",
		CXM_UNPIN_TAB: "unpin-tab",
		EXTENSION_GITHUB_LINK: "https://example.test/again-why-salesforce",
		HIDDEN_CLASS: "is-hidden",
		SALESFORCE_SETUP_HOME_MINI: "SetupOneHome/home",
		SETUP_LIGHTNING: "/lightning/setup/",
		TOAST_WARNING: "warning",
		TUTORIAL_EVENT_ACTION_FAVOURITE:
			"tutorial:actionFavourite:completed",
		TUTORIAL_EVENT_ACTION_UNFAVOURITE:
			"tutorial:actionUnfavourite:completed",
		TUTORIAL_EVENT_CLOSE_MANAGE_TABS: "tutorial:manageTabs:closed",
		TUTORIAL_EVENT_CREATE_MANAGE_TABS_MODAL:
			"tutorial:createManageTabsModal:completed",
		TUTORIAL_EVENT_PIN_TAB: "tutorial:pinTab:completed",
		TUTORIAL_EVENT_REORDERED_TABS_TABLE:
			"tutorial:tableReorder:completed",
		TUTORIAL_KEY: "tutorial-progress",
		WHAT_ADD: "add",
		WHAT_GET: "get",
		WHAT_GET_COMMANDS: "get-commands",
		WHAT_SET: "set",
	};
	const records = {
		redirects: [] as string[],
		messages: [] as Array<Record<string, unknown>>,
		toasts: [] as Array<{ message: string; status: string }>,
		latestUi: null as null | TutorialUi,
		actionButtonClicks: 0,
	};
	const storage = {
		[constants.TUTORIAL_KEY]: options.tutorialProgress ?? null,
	};
	const translator: Translator = {
		translate: async (key) => `translated:${key}`,
	};

	/**
	 * Creates one setup tab entry matching the structure expected by the tutorial.
	 *
	 * @param url Minified Salesforce Setup URL stored in the anchor title.
	 * @return List item containing the simulated setup link.
	 */
	function createSetupLink(url: string) {
		const li = globalThis.document.createElement("li");
		const link = globalThis.document.createElement("a");
		link.title = url;
		link.textContent = url;
		li.appendChild(link);
		return li;
	}

	/**
	 * Re-renders the mocked Setup tab list from the harness state.
	 */
	function renderSetupTabs() {
		setupTabUl.innerHTML = "";
		for (const url of state.savedTabUrls) {
			setupTabUl.appendChild(createSetupLink(url));
		}
	}

	/**
	 * Ensures the favourite star exists and is visible to hit-testing code.
	 *
	 * @return Visible favourite button element.
	 */
	function ensureVisibleFavouriteButton() {
		let button = globalThis.document.getElementById(
			"again-why-salesforce-star",
		) as HTMLInputElement | null;
		if (button == null) {
			button = globalThis.document.createElement("input");
			button.id = "again-why-salesforce-star";
			globalThis.document.body.appendChild(button);
		}
		button.getBoundingClientRect = () =>
			({
				width: 24,
				height: 24,
				top: 0,
				left: 0,
				right: 24,
				bottom: 24,
				x: 0,
				y: 0,
				toJSON: () => ({}),
			}) as DOMRect;
		return button;
	}

	/**
	 * Converts the current full URL into the minified Setup path used by the tutorial.
	 *
	 * @return Current Setup path without the origin prefix.
	 */
	function currentMiniUrl() {
		return globalThis.location.href.replace(
			/^https?:\/\/[^/]+\/lightning\/setup\//,
			"",
		);
	}

	/**
	 * Renders page-level fixtures needed for a given mocked Setup page.
	 *
	 * @param miniUrl Minified Setup URL being shown.
	 */
	function renderPage(miniUrl: string) {
		renderSetupTabs();
		const starButton = globalThis.document.getElementById(
			"again-why-salesforce-star",
		);
		if (miniUrl === constants.SALESFORCE_SETUP_HOME_MINI) {
			starButton?.remove();
			return;
		}
		ensureVisibleFavouriteButton();
	}

	/**
	 * Navigates the harness to a mocked Lightning Setup URL.
	 *
	 * @param miniUrl Minified Setup URL to visit.
	 */
	function navigateTo(miniUrl: string) {
		renderPage(miniUrl);
		globalThis.history.pushState(
			{},
			"",
			`${constants.SETUP_LIGHTNING}${miniUrl}`,
		);
	}

	/**
	 * Creates the minimal Manage Tabs modal DOM required by tutorial steps.
	 *
	 * @param rows Number of sortable rows rendered in the modal table.
	 * @return Root modal element.
	 */
	function createManageTabsModal(rows = state.savedTabUrls.length) {
		globalThis.document.getElementById("again-why-salesforce-modal")?.remove();
		const modal = globalThis.document.createElement("div");
		modal.id = "again-why-salesforce-modal";
		const table = globalThis.document.createElement("table");
		table.id = "sortable-table";
		const tbody = globalThis.document.createElement("tbody");
		for (let index = 0; index < rows; index++) {
			const row = globalThis.document.createElement("tr");
			const wrapCell = globalThis.document.createElement("td");
			const wrap = globalThis.document.createElement("div");
			wrap.className = "slds-cell-wrap";
			wrap.textContent = `Row ${index + 1}`;
			wrapCell.appendChild(wrap);
			row.appendChild(wrapCell);
			const actionCell = globalThis.document.createElement("td");
			const actionButton = globalThis.document.createElement("button");
			actionButton.dataset.action = constants.CXM_UNPIN_TAB;
			actionCell.appendChild(actionButton);
			row.appendChild(actionCell);
			tbody.appendChild(row);
		}
		table.appendChild(tbody);
		modal.appendChild(table);
		const saveButton = globalThis.document.createElement("button");
		saveButton.id = "again-why-salesforce-modal-confirm";
		modal.appendChild(saveButton);
		globalThis.document.body.appendChild(modal);
		return modal;
	}

	/**
	 * Updates harness state for a tutorial event and dispatches it on the document.
	 *
	 * @param eventName Tutorial custom event name to emit.
	 */
	function dispatchTutorialEvent(eventName: string) {
		switch (eventName) {
			case constants.TUTORIAL_EVENT_PIN_TAB:
				state.pinnedTabsNo = Math.max(state.pinnedTabsNo, 1);
				break;
			case constants.TUTORIAL_EVENT_ACTION_FAVOURITE: {
				const miniUrl = currentMiniUrl();
				if (!state.savedTabUrls.includes(miniUrl)) {
					state.savedTabUrls.push(miniUrl);
					renderSetupTabs();
				}
				break;
			}
			case constants.TUTORIAL_EVENT_ACTION_UNFAVOURITE: {
				const miniUrl = currentMiniUrl();
				state.savedTabUrls = state.savedTabUrls.filter((url) => url !== miniUrl);
				renderSetupTabs();
				break;
			}
		}
		globalThis.document.dispatchEvent(new globalThis.CustomEvent(eventName));
	}

	/**
	 * Waits until the visible tutorial message starts with the translated key.
	 *
	 * @param key Translation key expected in the message box.
	 * @return Resolves once the message box shows the requested step.
	 */
	async function waitForMessage(key: string) {
		await waitFor(() =>
			records.latestUi?.segments.textContent?.startsWith(
				`translated:${key}`,
			) === true
		);
	}

	const deps: TutorialDeps = {
		constants,
		functions: {
			performLightningRedirect: (url) => {
				records.redirects.push(url);
				const miniUrl = url.replace(/^\/lightning\/setup\//, "");
				navigateTo(miniUrl);
			},
			sendExtensionMessage: async (message) => {
				records.messages.push(message);
				switch (message.what) {
					case constants.WHAT_GET_COMMANDS:
						return [{ shortcut: "Ctrl+Shift+Y" }];
					case constants.WHAT_GET:
						return storage[message.key as string];
					case constants.WHAT_SET:
						storage[message.key as string] = message.set;
						return true;
					default:
						return null;
				}
			},
		},
		ensureTranslatorAvailability: async () => translator,
		Tab: {
			minifyURL: (url) =>
				url.replace(/^https?:\/\/[^/]+\/lightning\/setup\//, ""),
		},
		content: {
			getCurrentHref: () => globalThis.location.href,
			getSetupTabUl: () => setupTabUl,
			performActionOnTabs: (_action, redirectElement) => {
				if (!state.savedTabUrls.includes(redirectElement.url)) {
					state.savedTabUrls.push(redirectElement.url);
				}
				renderSetupTabs();
			},
			showToast: (message, status) => {
				records.toasts.push({ message, status });
			},
		},
		favouriteManager: {
			FAVOURITE_BUTTON_ID: "again-why-salesforce-star",
			showFavouriteButton: async () => {
				ensureVisibleFavouriteButton();
			},
		},
		generator: {
			MODAL_ID: "again-why-salesforce-modal",
			generateTutorialElements: async () => {
				const overlay = globalThis.document.createElement("div");
				const messageBox = globalThis.document.createElement("div");
				messageBox.className = "tut-v7";
				const segments = globalThis.document.createElement("div");
				const btnsParent = globalThis.document.createElement("div");
				btnsParent.classList.add(constants.HIDDEN_CLASS);
				const confirmBtn = globalThis.document.createElement("button");
				btnsParent.appendChild(confirmBtn);
				messageBox.appendChild(segments);
				messageBox.appendChild(btnsParent);
				const spinner = globalThis.document.createElement("div");
				spinner.classList.add(constants.HIDDEN_CLASS);
				const ui = {
					overlay,
					messageBox,
					spinner,
					segments,
					confirmBtn,
					btnsParent,
				};
				records.latestUi = ui;
				return ui;
			},
		},
		tabContainer: {
			ensureAllTabsAvailability: async () => {
				const allTabs = state.savedTabUrls.map((url) => ({ url }));
				(allTabs as Array<{ url: string }> & Record<string, number>)[
					"pinnedTabsNo"
				] = state.pinnedTabsNo;
				return allTabs;
			},
			TabContainer: {
				keyPinnedTabsNo: "pinnedTabsNo",
			},
		},
		manageTabs: {
			handleActionButtonClick: () => {
				records.actionButtonClicks++;
			},
		},
	};

	renderPage(constants.SALESFORCE_SETUP_HOME_MINI);

	return {
		constants,
		deps,
		dom,
		records,
		state,
		setupTabUl,
		storage,
		translator,
		createManageTabsModal,
		dispatchTutorialEvent,
		async load() {
			return await loadTutorialModule(deps);
		},
		navigateTo,
		waitForMessage,
		cleanup() {
			dom.cleanup();
		},
	};
}

Deno.test("checkTutorial starts the tutorial without a browser", async () => {
	const harness = createHarness({ tutorialProgress: null });
	const previousConfirm = globalThis.confirm;
	try {
		const tutorialModule = await harness.load();
		setGlobal("confirm", () => true);
		await tutorialModule.checkTutorial();
		await harness.waitForMessage("tutorial_restart");

		assertEquals(harness.records.redirects, ["/lightning/setup/SetupOneHome/home"]);
		assertExists(globalThis.document.querySelector(".tut-v7"));
		assertEquals(
			harness.records.latestUi?.segments.textContent,
			"translated:tutorial_restart",
		);
		assertEquals(harness.storage["tutorial-progress"], 0);
		assert(
			harness.records.messages.some((message) =>
				message.what === "get-commands"
			),
		);
	} finally {
		setGlobal("confirm", previousConfirm);
		await flush();
		harness.cleanup();
	}
});

Deno.test("executeStep advances on tutorial custom events", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.translator = harness.translator;
		await tutorial.createOverlay();

		const highlighted = globalThis.document.createElement("div");
		globalThis.document.body.appendChild(highlighted);

		let nextStepCalls = 0;
		tutorial.nextStep = () => {
			nextStepCalls++;
		};

		await tutorial.executeStep({
			message: "tutorial_add_favourite",
			element: async () => highlighted,
			action: "highlight",
			waitFor: "event",
			awaitsCustomEvent: harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
		});

		assert(highlighted.classList.contains("awsf-tutorial-highlight"));
		assert(tutorial.btnsParent.classList.contains(harness.constants.HIDDEN_CLASS));

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
		);

		assertEquals(nextStepCalls, 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("executeStep listens for Lightning navigation without a browser", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.translator = harness.translator;
		await tutorial.createOverlay();

		const target = globalThis.document.createElement("div");
		globalThis.document.body.appendChild(target);

		let nextStepCalls = 0;
		tutorial.nextStep = () => {
			nextStepCalls++;
		};

		await tutorial.executeStep({
			message: "tutorial_click_highlighted_tab",
			element: async () => target,
			action: "highlight",
			waitFor: "redirect",
		});

		assert(target.classList.contains("awsf-tutorial-highlight"));
		assert(tutorial.btnsParent.classList.contains(harness.constants.HIDDEN_CLASS));

		harness.navigateTo("ObjectManager/Account/FieldsAndRelationships/view");
		await flush();

		assertEquals(nextStepCalls, 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("tutorial runs end to end and persists completion without a browser", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		await tutorial.start();
		await harness.waitForMessage("tutorial_restart");
		assertEquals(tutorial.currentStep, 0);
		assertEquals(harness.storage["tutorial-progress"], 0);

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_favourite_tabs");

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_click_highlighted_tab");

		harness.navigateTo("ObjectManager/Account/FieldsAndRelationships/view");
		await harness.waitForMessage("tutorial_remove_favourite");

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_ACTION_UNFAVOURITE,
		);
		await harness.waitForMessage("tutorial_redirect_account");

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_add_favourite");

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_ACTION_FAVOURITE,
		);
		await harness.waitForMessage("tutorial_pin_tab");

		harness.dispatchTutorialEvent(harness.constants.TUTORIAL_EVENT_PIN_TAB);
		await harness.waitForMessage("tutorial_pinned_tab");

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_manage_tabs");

		harness.createManageTabsModal();
		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_CREATE_MANAGE_TABS_MODAL,
		);
		await harness.waitForMessage("tutorial_manage_tabs_link");

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_drag_flows");

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_REORDERED_TABS_TABLE,
		);
		await harness.waitForMessage("tutorial_pinned_explanation");

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_save_modal");

		harness.dispatchTutorialEvent(
			harness.constants.TUTORIAL_EVENT_CLOSE_MANAGE_TABS,
		);
		await harness.waitForMessage("tutorial_keyboard_shortcut");
		assert(
			harness.records.latestUi?.segments.textContent?.includes(
				"Shortcut: Ctrl+Shift+Y",
			),
		);

		await advanceCurrentStep(tutorial);
		await harness.waitForMessage("tutorial_end");
		assertEquals(harness.records.latestUi?.confirmBtn.textContent, "translated:close");

		await advanceCurrentStep(tutorial);
		await waitFor(() => !tutorial.isActive);

		assertEquals(harness.storage["tutorial-progress"], tutorial.steps.length);
		assertEquals(globalThis.document.querySelector(".tut-v7"), null);
		assert(
			harness.records.redirects.includes("/lightning/setup/PermSets/home"),
		);
		assertEquals(harness.state.pinnedTabsNo, 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("checkTutorial resumes from stored progress without a browser", async () => {
	const harness = createHarness({ tutorialProgress: 6 });
	const previousConfirm = globalThis.confirm;
	try {
		const tutorialModule = await harness.load();
		setGlobal("confirm", () => true);
		await tutorialModule.checkTutorial();
		await harness.waitForMessage("tutorial_add_favourite");

		assertEquals(harness.records.redirects, [
			"/lightning/setup/ObjectManager/Account/FieldsAndRelationships/view",
		]);
		assertEquals(harness.storage["tutorial-progress"], 5);
		assert(
			harness.records.latestUi?.segments.textContent?.includes(
				"translated:tutorial_add_favourite",
			),
		);
	} finally {
		setGlobal("confirm", previousConfirm);
		await flush();
		harness.cleanup();
	}
});

Deno.test("executeStep resets to the nearest starting block when a required element is missing", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.translator = harness.translator;
		await tutorial.createOverlay();
		tutorial.steps = [
			{ message: "block_zero", beginsBlock: true },
			{ message: "inside_zero" },
			{ message: "block_two", beginsBlock: true },
			{ message: "inside_two" },
			{ message: "current_step" },
		];
		tutorial.currentStep = 4;

		let restartFromStep: number | null = null;
		tutorial.nextStep = () => {
			tutorial.currentStep++;
			restartFromStep = tutorial.currentStep;
		};

		await tutorial.executeStep({
			message: "missing_element_step",
			element: async () => null,
		});

		assertEquals(harness.records.toasts, [{
			message: "tutorial_step_was_missed",
			status: "warning",
		}]);
		assertEquals(restartFromStep, 2);
		assertEquals(tutorial.currentStep, 2);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("initSteps returns false and shows a toast when no redirect links are available", async () => {
	const harness = createHarness({
		savedTabUrls: ALL_USABLE_PAGE_URLS,
	});
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();

		const initialized = await tutorial.initSteps();

		assertEquals(initialized, false);
		assertEquals(harness.records.toasts, [{
			message: "tutorial_export_and_reset_for_tutorial",
			status: "warning",
		}]);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("persistTutorialProgress validates input and clamps the last step to completion", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.steps = [{}, {}, {}];
		tutorial.currentStep = 2;

		assertThrows(
			() => tutorial.persistTutorialProgress("bad"),
			TypeError,
			"stepNo should be a number",
		);

		await tutorial.persistTutorialProgress();
		assertEquals(harness.storage["tutorial-progress"], 3);

		await tutorial.persistTutorialProgress(1);
		assertEquals(harness.storage["tutorial-progress"], 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("showMessage appends link and shortcut only when they are not already present", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		await tutorial.createOverlay();
		tutorial.translator = {
			translate: async (key) => {
				if (key === "already_complete") {
					return "Message with https://docs.test and Shortcut: Alt+K";
				}
				return "Base message";
			},
		};

		tutorial.showSpinner();
		await tutorial.showMessage({
			message: "base",
			link: "https://docs.test",
			shortcut: "Alt+K",
		});
		assertEquals(
			tutorial.segments.textContent,
			"Base message\n\nhttps://docs.test\n\nShortcut: Alt+K",
		);
		assert(tutorial.spinner.classList.contains(harness.constants.HIDDEN_CLASS));

		await tutorial.showMessage({
			message: "already_complete",
			link: "https://docs.test",
			shortcut: "Alt+K",
		});
		assertEquals(
			tutorial.segments.textContent,
			"Message with https://docs.test and Shortcut: Alt+K",
		);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("getElementNowOrLater creates a fake element after enough retries", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		const fakeEl = globalThis.document.createElement("div");
		let callbackCalls = 0;
		tutorial.retryCount = 5;

		const result = await tutorial.getElementNowOrLater({
			element: async () => null,
			fakeElement: async () => fakeEl,
		}, () => {
			callbackCalls++;
		});

		assertEquals(result, fakeEl);
		assertEquals(tutorial.retryCount, 6);
		assertEquals(callbackCalls, 0);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("getElementNowOrLater schedules a retry when the element is still missing", async () => {
	const harness = createHarness();
	const originalSetTimeout = globalThis.setTimeout;
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		const scheduled = [] as Array<{ delay: number; callback: () => void }>;
		setGlobal("setTimeout", ((callback: () => void, delay: number) => {
			scheduled.push({ delay, callback });
			return 1;
		}) as typeof setTimeout);

		let callbackCalls = 0;
		const step = {
			element: async () => null,
			fakeElement: async () => null,
		};

		const result = await tutorial.getElementNowOrLater(step, (receivedStep) => {
			assertEquals(receivedStep, step);
			callbackCalls++;
		});

		assertEquals(result, undefined);
		assertEquals(tutorial.retryCount, 1);
		assertEquals(scheduled.length, 1);
		assertEquals(scheduled[0].delay, 1000);

		scheduled[0].callback();
		assertEquals(callbackCalls, 1);
	} finally {
		setGlobal("setTimeout", originalSetTimeout);
		await flush();
		harness.cleanup();
	}
});

Deno.test("end(false) cleans up the UI without overwriting stored progress", async () => {
	const harness = createHarness({ tutorialProgress: 4 });
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.steps = [{}, {}, {}];
		tutorial.isActive = true;
		await tutorial.createOverlay();
		const highlighted = globalThis.document.createElement("div");
		globalThis.document.body.appendChild(highlighted);
		tutorial.highlightElement(highlighted);

		tutorial.end(false);

		assertEquals(tutorial.isActive, false);
		assertEquals(globalThis.document.querySelector(".tut-v7"), null);
		assert(!highlighted.classList.contains("awsf-tutorial-highlight"));
		assertEquals(harness.storage["tutorial-progress"], 4);
	} finally {
		await flush();
		harness.cleanup();
	}
});

Deno.test("checkTutorial marks the tutorial completed when the user declines the first prompt", async () => {
	const harness = createHarness({ tutorialProgress: null });
	const previousConfirm = globalThis.confirm;
	try {
		const tutorialModule = await harness.load();
		setGlobal("confirm", () => false);

		await tutorialModule.checkTutorial();
		await waitFor(() => harness.storage["tutorial-progress"] != null);

		assertEquals(harness.storage["tutorial-progress"], 15);
		assertEquals(harness.records.redirects, []);
		assertEquals(globalThis.document.querySelector(".tut-v7"), null);
	} finally {
		setGlobal("confirm", previousConfirm);
		await flush();
		harness.cleanup();
	}
});

Deno.test("checkTutorial marks the tutorial completed when the user declines to continue", async () => {
	const harness = createHarness({ tutorialProgress: 3 });
	const previousConfirm = globalThis.confirm;
	try {
		const tutorialModule = await harness.load();
		setGlobal("confirm", () => false);

		await tutorialModule.checkTutorial();
		await waitFor(() => harness.storage["tutorial-progress"] === 15);

		assertEquals(harness.records.redirects, []);
		assertEquals(globalThis.document.querySelector(".tut-v7"), null);
	} finally {
		setGlobal("confirm", previousConfirm);
		await flush();
		harness.cleanup();
	}
});

Deno.test("nextStep configures the ending step and triggers confetti", async () => {
	const harness = createHarness();
	try {
		const tutorialModule = await harness.load();
		const tutorial = new tutorialModule.Tutorial();
		tutorial.translator = harness.translator;
		await tutorial.createOverlay();
		tutorial.steps = [{
			message: "tutorial_end",
			beginsBlock: true,
			isEndingStep: true,
			waitFor: "confirm",
		}];
		tutorial.currentStep = -1;

		let confettiCalls = 0;
		tutorial.throwConfetti = () => {
			confettiCalls++;
		};

		await tutorial.nextStep();

		assertEquals(tutorial.currentStep, 0);
		assertEquals(tutorial.confirmBtn.textContent, "translated:close");
		assertEquals(confettiCalls, 1);
		assertEquals(harness.storage["tutorial-progress"], 1);
	} finally {
		await flush();
		harness.cleanup();
	}
});
