name: Build extension single browser

on:
    workflow_call:
        inputs:
            target_browser:
                description: "The broswer for which to build the extension"
                required: true
                type: string
            target_file:
                description: "The file path and name for the release"
                required: true
                type: string

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Make ${{ inputs.target_browser }} Manifest
              run: deno run dev-${{ inputs.target_browser }}

            - name: Zip ${{ inputs.target_browser }} extension
              run: zip -r ${{ inputs.target_file }}\
                action assets background salesforce *.js LICENSE.txt README.md manifest.json\
                -x "*/README.md"

            - name: Create ${{ inputs.target_browser }} Release
              uses: softprops/action-gh-release@v1
              with:
                files: ${{ inputs.target_file }}
