name: Build and add to PR

on:
    pull_request:
        types:
            - closed
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Extract current version
              run: |
                  VERSION=$(grep -oP '"version":\s*"\K[0-9.]+' manifest/template-manifest.json)
                  echo "BRANCH_NAME=new-version-$VERSION" >> $GITHUB_ENV

            - name: Trigger Build
              uses: ./.github/workflows/build.yml
              with:
                  target_branch: ${{ github.event_name == 'workflow_dispatch' && '${{ env.BRANCH_NAME }}' || github.event.pull_request.base.ref }}
