name: Format, Lint and add changes on PR

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Switch to branch
              run: |
                git fetch origin "${{ github.head_ref }}" 
                git switch "${{ github.head_ref }}"
                chmod +x .github/scripts/task-and-push-when-diff.sh

            - name: Sort locales
              continue-on-error: true
              run: .github/scripts/task-and-push-when-diff.sh sort locales-errors.log

            - name: Comment on PR if sorter fails
              uses: actions/github-script@v7
              with:
                script: |
                  const handler = require('./.github/scripts/comment-on-pr.js');
                  await handler({
                    github,
                    context,
                    core,
                    logFile: 'locales-errors.log',
                    title:   'Locale Sorter Failed',
                    matchPattern: /^(?:✖  Failed .+?: .+|Error traversing .+?: .+|Unexpected error: .+)/m,
                    stripPatterns: [
                      /^✔  Sorted .+\n/gm
                    ]
                  });

            - name: Run linter
              continue-on-error: true
              run: deno task lint 2> lint-error.log

            - name: Comment on PR if linter fails
              uses: actions/github-script@v7
              with:
                script: |
                  const handler = require('./.github/scripts/comment-on-pr.js');
                  await handler({
                    github,
                    context,
                    core,
                    logFile: 'lint-error.log',
                    title:   'Linter Failed',
                    matchPattern: /Found [0-9]+ problem/,
                    stripPatterns: [
                      /^Download https:\/\/.*\n/gm
                    ]
                  });

            - name: Run tests
              continue-on-error: true
              run: deno task test > test-error.log 2>&1

            - name: Comment on PR if any test fails
              uses: actions/github-script@v7
              with:
                script: |
                  const handler = require('./.github/scripts/comment-on-pr.js');
                  await handler({
                    github,
                    context,
                    core,
                    logFile: 'test-error.log',
                    title:   'Tests Failed',
                    matchPattern: /FAILED \| [0-9]+ passed .* \| [0-9]+ failed/,
                    stripPatterns: [
                      /^\.\/tests\/.+ ok \([0-9]+ms\)\n/gm
                    ]
                  });

            - name: Run formatter
              run: .github/scripts/task-and-push-when-diff.sh fmt
