name: Format, Lint and add changes on PR

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review
        branches:
            - main

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Switch to branch
              run: |
                git fetch origin "${{ github.head_ref }}" 
                git switch "${{ github.head_ref }}"

            - name: Run linter and comment on failure
              uses: actions/github-script@v7
              with:
                script: |
                  try {
                    // Run the lint task and capture the output
                    const process = Deno.run({
                      cmd: ["deno", "task", "lint"],
                      stderr: "piped"
                    });

                    const errorOutput = new TextDecoder().decode(await process.stderrOutput());

                    // Combine both standard output and error output

                    if (errorOutput.length === 0)
                      return;

                    // Extract PR number from GitHub event path
                    const eventPath = Deno.env.get("GITHUB_EVENT_PATH");
                    const eventData = JSON.parse(await Deno.readTextFile(eventPath));
                    const prNumber = eventData.pull_request.number;

                    // Output the PR number
                    console.log(prNumber);
                    console.log(context.issue.number);

                    // Write comment
                    github.rest.issues.createComment({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: `## Linter Failed:\n\n\`\`\`${errorOutput}\`\`\`` 
                    });

                  } catch (error) {
                    console.error("Error running lint task:", error);
                  }

            - name: Verify formatting
              run: deno task fmt

            - name: Ensure Changes Exist
              run: |
                  if git diff --exit-code; then
                    echo "No changes to commit, exiting."
                    exit 0
                  fi

            - name: Set up Git user
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"

            - name: Push fmt changes
              run: |
                  git commit -am "deno formatting"
                  git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} "${{ github.head_ref }}"
